### DO NOT EDIT THIS FILE ###

from pypdevs.DEVS import AtomicDEVS
import random

# ============================================================================
# NOTE: This version of PyPDEVS requires outputs to be wrapped in lists.
# You will see [value] instead of just value in outputFnc() methods.
# Inputs are automatically unwrapped, but we check with isinstance() to be safe.
# See the comments in atomicdevs.py for more details.
# ============================================================================

class Product:
    """
    Represents a product in the manufacturing system.
    
    Attributes:
        size (int): The size of the product (e.g., 1 or 2)
        recipe (list): The sequence of machine operations (e.g., ['A', 'B'] or ['B', 'A'])
        current_step (int): The current step in the recipe (0-indexed)
        arrival_time (float): The time when the product entered the system
    """
    def __init__(self, size, recipe, creation_time):
        self.size = size
        self.recipe = recipe
        self.current_step = 0
        self.arrival_time = creation_time
    
    def __repr__(self):
        return f"Product(size={self.size}, recipe={self.recipe}, step={self.current_step})"

class GeneratorState:
    def __init__(self, gen_num, seed=0):
        # Current simulation time
        self.current_time = 0.0
        # Remaining time until generation of new product
        self.remaining = 0.0
        # Counter on how many products to generate still
        self.to_generate = gen_num
        # Next product to output
        self.next_product = None
        # State of our random number generator
        self.random = random.Random(seed)

class Generator(AtomicDEVS):
    """
    Generator creates products at pseudo-random time intervals.
    
    Parameters:
        seed (int): Seed for the random number generator
        lambd (float): Rate parameter for exponential distribution (products/second)
        gen_types (list of tuples): List of (size, recipe) tuples defining product types
                                     E.g., [(1, ['A', 'B']), (1, ['A', 'B']), (2, ['B', 'A'])]
        gen_num (int): Total number of products to generate
    
    Output Ports:
        out_product: Outputs a Product object when generated
    """
    def __init__(self, seed=0, lambd=1.0/60.0/4.0, gen_types=[(1, ['A', 'B']), (1, ['A', 'B']), (2, ['B', 'A'])], gen_num=500):
        super().__init__("Generator")
        
        # Output port for the product
        self.out_product = self.addOutPort("out_product")
        
        # Parameters
        self.lambd = lambd
        self.gen_types = gen_types
        
        # Initialize state
        self.state = GeneratorState(gen_num, seed)
        self._nextProduct()  # Schedule the first product
    
    def _nextProduct(self):
        # Randomly select a product type from gen_types
        size, recipe = self.state.random.choice(self.gen_types)
        # Calculate creation time
        creation = self.state.current_time + self.state.remaining
        # Update state
        self.state.next_product = Product(size, recipe, creation)
        self.state.remaining = self.state.random.expovariate(self.lambd)
    
    def intTransition(self):
        # Update simulation time
        self.state.current_time += self.timeAdvance()
        # Update number of generated products
        self.state.to_generate -= 1
        if self.state.to_generate == 0:
            # Already generated enough products, so stop
            self.state.remaining = float('inf')
            self.state.next_product = None
        else:
            # Still have to generate products, so sample for new duration
            self._nextProduct()
        return self.state
    
    def timeAdvance(self):
        # Return remaining time; infinity when generated enough
        return self.state.remaining
    
    def outputFnc(self):
        # Output the new product on the output port (wrap in list for PyPDEVS)
        return {self.out_product: [self.state.next_product]}


class SinkState:
    def __init__(self):
        # Contains received products and simulation time
        self.products = []
        self.current_time = 0.0

class Sink(AtomicDEVS):
    """
    Sink collects finished products and computes statistics.
    
    For each product, it computes the total time spent in the system
    (current_time - arrival_time).
    
    Input Ports:
        in_product: Receives finished Product objects
    """
    def __init__(self):
        super().__init__("Sink")
        self.state = SinkState()
        # Has only one input port
        self.in_product = self.addInPort("in_product")
    
    def extTransition(self, inputs):
        # Update simulation time
        self.state.current_time += self.elapsed
        # Get the product
        product = inputs[self.in_product]
        # PyPDEVS unwraps single-element lists automatically
        if isinstance(product, list):
            product = product[0]
        # Calculate time in system (flow time)
        flow_time = self.state.current_time - product.arrival_time
        product.flow_time = flow_time
        # Add incoming product to received products
        self.state.products.append(product)
        return self.state
    
    # Don't define anything else, as we only store products.
    # Sink has no behaviour of its own.

### END OF PROVIDED CODE - DO NOT EDIT ###
